/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'linkedin' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Education = IDL.Record({
  'field' : IDL.Text,
  'endDate' : IDL.Text,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Resume = IDL.Record({
  'contact' : ContactInfo,
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'summary' : IDL.Text,
  'updatedAt' : Timestamp,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'loadResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'saveResume' : IDL.Func([Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'linkedin' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Education = IDL.Record({
    'field' : IDL.Text,
    'endDate' : IDL.Text,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Resume = IDL.Record({
    'contact' : ContactInfo,
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'summary' : IDL.Text,
    'updatedAt' : Timestamp,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'loadResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'saveResume' : IDL.Func([Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };